name: main

on:
  push:
    paths-ignore:
      - '.github/workflows/test-*'
      - 'test/alpine/**'
      - 'test/debian/**'
      - 'test/fedora/**'
      - 'README.md'
  pull_request:
  workflow_dispatch:
    
jobs:
  build:
    name: Build

    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      -
        name: Checkout
        uses: actions/checkout@v7.0.1

      -
        name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
      
      - 
        name: Check Go format
        run: |
          gofmtout=$(gofmt -l .); [ -z "${gofmtout}" ] || { echo "Detected malformatted go files. Run 'go fmt ./..." >&2; echo $gofmtout; exit 1; }
      
      -
        name: Get dependencies
        run: |
          go mod download

      - 
        name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v2.0.2
        with:
          tofu_version: "1.13.1"
          tofu_wrapper: false

      - 
        name: Verify generated files
        run: |
          go generate ./...;
          git diff --compact-summary --exit-code || (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

      -
        name: Build
        run: |
          go build -v .
      
      -
        name: Run unit tests
        run: |
          go test -v ./...
  
  acctest:
    name: Acceptance test (${{ matrix.target.name }}, tofu ${{ matrix.tofu_version }})
    
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        target:
          - 
            name: alpine
            test_path: test/alpine
            host_port: 10022
            private_key_file: root-ed25519
            extra_run_args: --tmpfs /tmp --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro
          - 
            name: debian
            test_path: test/debian
            host_port: 11022
            private_key_file: root-ed25519
            extra_run_args: --tmpfs /tmp --tmpfs /run --tmpfs /run/lock --mount type=bind,source=/sys/fs/cgroup,target=/sys/fs/cgroup --cgroupns=host
          - 
            name: fedora
            test_path: test/fedora
            host_port: 12022
            private_key_file: root-ed25519
            extra_run_args: --tmpfs /tmp --tmpfs /run --tmpfs /run/lock --mount type=bind,source=/sys/fs/cgroup,target=/sys/fs/cgroup --cgroupns=host
        tofu_version:
          - '1.12.6'
          - '1.13.1'
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v7.0.1
      
      - 
        name: Context variables
        id: vars
        run: |
          echo "os_container_name=terraform-provider-system-${{ matrix.target.name }}-${{ github.run_id }}" >> $GITHUB_OUTPUT
          echo "os_image_name=terraform-provider-system-${{ matrix.target.name }}-acctest:${{ github.run_id }}" >> $GITHUB_OUTPUT
      
      -
        name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod

      -
        # The image is built from the repository instead of pulled from a registry to run the acceptance tests without access to a registry, e.g. in forks
        name: Build ${{ matrix.target.name }} container image
        run: >
          docker build
          --file ${{ matrix.target.test_path }}/docker/Dockerfile
          --tag '${{ steps.vars.outputs.os_image_name }}'
          ${{ matrix.target.test_path }}/docker

      -
        # Note: services cannot be used for the purpose of running the test os container because, required files from the repository checkout are not available at the time the service containers are started
        name: Start ${{ matrix.target.name }} container
        id: start_os_container
        run: >
          sudo chown root:root ${{ github.workspace }}/${{ matrix.target.test_path }}/${{ matrix.target.private_key_file }}.pub;
          sudo chmod 600 ${{ matrix.target.test_path }}/${{ matrix.target.private_key_file }} ${{ matrix.target.test_path }}/${{ matrix.target.private_key_file }}.pub;
          docker run
          --detach
          --rm
          --name '${{ steps.vars.outputs.os_container_name }}'
          --env 'SSH_ENABLE_ROOT_PASSWORD_AUTH=true'
          --env 'SSH_ENABLE_PASSWORD_AUTH=true'
          --env 'TCP_FORWARDING=true'
          --publish ${{ matrix.target.host_port }}:22
          --mount type=bind,source=${{ github.workspace }}/${{ matrix.target.test_path }}/${{ matrix.target.private_key_file }}.pub,target=/etc/authorized_keys/root,readonly
          --mount type=bind,source=${{ github.workspace }}/${{ matrix.target.test_path }}/hostkeys,target=/etc/ssh/keys
          ${{ matrix.target.extra_run_args }}
          ${{ steps.vars.outputs.os_image_name }}

      - 
        # The wrapper is disabled because the acceptance test framework runs the executable directly
        name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v2.0.2
        with:
          tofu_version: ${{ matrix.tofu_version }}
          tofu_wrapper: false

      -
        name: Run acceptance tests
        env:
          TF_ACC: "1"
          TF_LOG: "DEBUG"
          TF_ACC_PROVIDER_HOST: registry.opentofu.org
          TF_ACC_PROVIDER_SYSTEM_TARGETS: ${{ matrix.target.name }}
        run: |
          TF_ACC_TERRAFORM_PATH="$(command -v tofu)" go test -v ./internal/provider/

      -
        name: Logs of ${{ matrix.target.name }} container
        if: ${{ always() && steps.start_os_container.outcome == 'success' }}
        continue-on-error: true
        run: >
          docker logs '${{ steps.vars.outputs.os_container_name }}'

      -
        name: Stop ${{ matrix.target.name }} container
        if: ${{ always() && steps.start_os_container.outcome == 'success' }}
        continue-on-error: true
        run: >
          docker stop --time 30 '${{ steps.vars.outputs.os_container_name }}'

  release:
    name: Release
    
    # only on push events and if commit has version tag
    if: ${{ github.repository == 'neuspaces/terraform-provider-system' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}

    needs: acctest
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      -
        name: Checkout
        uses: actions/checkout@v7.0.1

      -
        name: Unshallow
        run: git fetch --prune --unshallow

      -
        name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod

      -
        name: Import GPG private key
        id: import_gpg_private_key
        uses: neuspaces/gpg-key-action@v6.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg_private_key.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}